[project]
name = "codereviewer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.116.1",
    "langchain>=0.3.26",
    "langgraph>=0.5.3",
    "networkx>=3.5",
]
