from enum import StrEnum


class ModuleType(StrEnum):
    OBJECT = "Модуль объектов"
    MANAGER = "Модуль менеджера"
    FORM = "Модуль формы"
    SESSION = "Модуль сеанса"


class MetadataType(StrEnum):
    """Enum types of metadata objects"""
    CATALOG = "Catalog"
    DOCUMENT = "Document"
    ENUM = "Enum"
    URL_TEMPLATE = "URLTemplate"
    BUSINESS_PROCESS = "BusinessProcess"
    TASK = "Task"
    REPORT = "Report"
    METHOD = "Method"
    DATA_PROCESSOR = "DataProcessor"
    CHART_OF_ACCOUNTS = "ChartOfAccounts"
    INFORMATION_REGISTER = "InformationRegister"
    ACCUMULATION_REGISTER = "AccumulationRegister"
    ACCOUNTING_REGISTER = "AccountingRegister"
    CALCULATION_REGISTER = "CalculationRegister"
    EXCHANGE_PLAN = "ExchangePlan"
    SEQUENCE = "Sequence"
    DOCUMENT_JOURNAL = "DocumentJournal"
    FILTER_CRITERION = "FilterCriterion"
    STYLE = "Style"
    XDTO_PACKAGE = "XDTOPackage"
    WEB_SERVICE = "WebService"
    HTTP_SERVICE = "HTTPService"
    FORM = "Form"
    COMMAND_GROUP = "CommandGroup"
    TEMPLATE = "Template"
    SESSION_PARAMETER = "SessionParameter"
    SETTINGS_STORAGE = "SettingsStorage"
    ROLE = "Role"
    SCHEDULED_JOB = "ScheduledJob"
    EXTERNAL_DATA_SOURCE = "ExternalDataSource"
    EXTERNAL_DATA_TABLE = "ExternalDataTable"
